#!/usr/bin/env python3
"""
heos_weekly_audit.py — cotygodniowy audyt HEOS Skills + Profil Hermesa.

Generuje raport i (opcjonalnie) wysyła na Discord przez webhook lub stdout.

Użycie:
    python3 heos_weekly_audit.py                 # tylko stdout
    python3 heos_weekly_audit.py --webhook URL   # + Discord webhook
    python3 heos_weekly_audit.py --save          # + zapis do HEOS/03-quality/
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


HEOS_ROOT = Path("/home/gaja/gaja-projekty/HEOS")
HERMES_SKILLS = Path("/home/gaja/.hermes/profiles/gaja/skills")


def _run_audit(target: Path) -> dict:
    """Uruchom skill_audit.py na danym katalogu i zwróć statystyki."""
    # HEOS v1.2 layout: tools/skill_audit.py (nie 03-quality/skill_audit.py z v1.1)
    audit_script = HEOS_ROOT / "tools" / "skill_audit.py"
    if not audit_script.exists():
        return {"error": f"audit script not found: {audit_script}"}
    try:
        result = subprocess.run(
            [sys.executable, str(audit_script), str(target), "--quiet"],
            capture_output=True,
            text=True,
            timeout=60,
        )
        # Parsuj podsumowanie
        # Format: "Schema: ✅ 5 PASS | ⚠️  0 WARN | ❌ 0 FAIL"
        # Format: "Zbadane Skills: 5"
        stats = {"pass": 0, "warn": 0, "fail": 0, "total": 0}
        for line in result.stdout.splitlines():
            line = line.strip()
            if line.startswith("Zbadane Skills:"):
                # "Zbadane Skills: 5"
                try:
                    stats["total"] = int(line.rsplit(":", 1)[1].strip())
                except (ValueError, IndexError):
                    pass
            elif line.startswith("Schema:"):
                # "Schema: ✅ 5 PASS | ⚠️  0 WARN | ❌ 0 FAIL"
                # Szukamy wzorca "N PASS"
                import re
                m_pass = re.search(r"(\d+)\s*PASS", line)
                m_warn = re.search(r"(\d+)\s*WARN", line)
                m_fail = re.search(r"(\d+)\s*FAIL", line)
                if m_pass:
                    stats["pass"] = int(m_pass.group(1))
                if m_warn:
                    stats["warn"] = int(m_warn.group(1))
                if m_fail:
                    stats["fail"] = int(m_fail.group(1))
        return stats
    except subprocess.TimeoutExpired:
        return {"error": "audit timeout"}


def _emoji_bar(passed: int, total: int) -> str:
    """Pasek postępu: ████░░░░ 50%"""
    if total == 0:
        return "░░░░░░░░░░ 0%"
    pct = 100 * passed // total
    filled = pct // 10
    bar = "█" * filled + "░" * (10 - filled)
    return f"{bar} {pct}%"


def build_report(heos_stats: dict, hermes_stats: dict) -> str:
    """Zbuduj raport markdown do Discorda."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = [f"## 📊 HEOS Weekly Audit — {now}", ""]

    # HEOS Skills
    if heos_stats.get("error"):
        lines.append(f"❌ **HEOS audit error:** {heos_stats['error']}")
    else:
        total = heos_stats["total"]
        passed = heos_stats["pass"]
        bar = _emoji_bar(passed, total)
        status_emoji = "🟢" if passed == total and total > 0 else "🟡" if passed > 0 else "🔴"
        lines.append(f"### HEOS (nowe Skillsy)")
        lines.append(f"{status_emoji} **{passed}/{total} PASS**  `{bar}`")
        lines.append("")

    # Hermes Profile Skills
    if hermes_stats.get("error"):
        lines.append(f"❌ **Hermes profile audit error:** {hermes_stats['error']}")
    else:
        total = hermes_stats["total"]
        passed = hermes_stats["pass"]
        bar = _emoji_bar(passed, total)
        status_emoji = "🟢" if passed == total and total > 0 else "🔴"
        lines.append(f"### Hermes Profile (87 Skills)")
        lines.append(f"{status_emoji} **{passed}/{total} PASS**  `{bar}`")
        if total > 0 and passed < total:
            to_go = total - passed
            lines.append(f"_⚠️  {to_go} Skills do uzupełnienia_")
        lines.append("")

    lines.append("---")
    lines.append("_Auto-generated by `heos_weekly_audit.py` (cron: every 7 days)_")
    return "\n".join(lines)


def post_webhook(url: str, content: str) -> bool:
    """Wyślij wiadomość na Discord webhook. Zwraca True/False."""
    import urllib.request
    import urllib.error

    payload = json.dumps({"content": content}).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=payload,
        headers={"Content-Type": "application/json", "User-Agent": "HEOS-Audit/1.0"},
    )
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            return 200 <= resp.status < 300
    except (urllib.error.URLError, urllib.error.HTTPError, OSError) as e:
        print(f"webhook error: {e}", file=sys.stderr)
        return False


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--webhook",
        default=os.environ.get("HEOS_DISCORD_WEBHOOK"),
        help="Discord webhook URL (lub env: HEOS_DISCORD_WEBHOOK)",
    )
    parser.add_argument(
        "--save",
        action="store_true",
        help="Zapisz raport do HEOS/03-quality/weekly-reports/",
    )
    args = parser.parse_args()

    print("[HEOS] Running weekly audit...")
    heos_stats = _run_audit(HEOS_ROOT)
    hermes_stats = _run_audit(HERMES_SKILLS)

    report = build_report(heos_stats, hermes_stats)
    print(report)
    print()

    # Save do pliku
    if args.save:
        out_dir = HEOS_ROOT / "03-quality" / "weekly-reports"
        out_dir.mkdir(parents=True, exist_ok=True)
        stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        out_path = out_dir / f"audit-{stamp}.md"
        out_path.write_text(report, encoding="utf-8")
        print(f"[HEOS] Saved to {out_path}")

    # Discord webhook
    if args.webhook:
        # Discord limit 2000 znaków na wiadomość
        if len(report) <= 1900:
            ok = post_webhook(args.webhook, report)
            print(f"[HEOS] Discord webhook: {'OK' if ok else 'FAILED'}")
            return 0 if ok else 1
        else:
            print(f"[HEOS] Report too long for Discord ({len(report)} chars), skipping webhook")
            return 0

    return 0


if __name__ == "__main__":
    sys.exit(main())
